// Code generated by MockGen. DO NOT EDIT.
// Source: linuxserver.go

// Package mocks is a generated GoMock package.
package mocks

import (
	linuxserver "pluggin-engine/internal/linuxserver"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetLinuxServerData mocks base method.
func (m *MockService) GetLinuxServerData() (linuxserver.MockLinuxServerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinuxServerData")
	ret0, _ := ret[0].(linuxserver.MockLinuxServerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinuxServerData indicates an expected call of GetLinuxServerData.
func (mr *MockServiceMockRecorder) GetLinuxServerData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinuxServerData", reflect.TypeOf((*MockService)(nil).GetLinuxServerData))
}
