// Code generated by MockGen. DO NOT EDIT.
// Source: switch.go

// Package mocks is a generated GoMock package.
package mocks

import (
	_switch "pluggin-engine/internal/switch"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetSwitchData mocks base method.
func (m *MockService) GetSwitchData() (_switch.MockSwitchData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSwitchData")
	ret0, _ := ret[0].(_switch.MockSwitchData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSwitchData indicates an expected call of GetSwitchData.
func (mr *MockServiceMockRecorder) GetSwitchData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSwitchData", reflect.TypeOf((*MockService)(nil).GetSwitchData))
}
