// Code generated by MockGen. DO NOT EDIT.
// Source: loadbalancer.go

// Package mocks is a generated GoMock package.
package mocks

import (
	loadbalancer "pluggin-engine/internal/loadbalancer"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetLoadBalancerData mocks base method.
func (m *MockService) GetLoadBalancerData() (loadbalancer.MockLoadBalancerData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLoadBalancerData")
	ret0, _ := ret[0].(loadbalancer.MockLoadBalancerData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLoadBalancerData indicates an expected call of GetLoadBalancerData.
func (mr *MockServiceMockRecorder) GetLoadBalancerData() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLoadBalancerData", reflect.TypeOf((*MockService)(nil).GetLoadBalancerData))
}
